# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesafioTechFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesafioTechFit
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftGifOrigin'
  pod 'paper-onboarding'

  target 'DesafioTechFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
